[[describe.args]]
type = "string"

[[describe.args]]
type = "function"

[[expect.args]]
type = "any"

[[it.args]]
type = "string"

[[it.args]]
type = "function"

[[itFOCUS.args]]
type = "string"

[[itFOCUS.args]]
type = "function"

[[itSKIP.args]]
type = "string"

[[itSKIP.args]]
type = "function"
required = false

[[afterEach.args]]
type = "function"

[[beforeEach.args]]
type = "function"

[[afterAll.args]]
type = "function"

[[beforeAll.args]]
type = "function"

[__LEMUR__]
property = true